name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v1
      - name: Install modules
        run: yarn
      - name: Run tests
        run: PORT=5000 GOOGLE_APPLICATION_CREDENTIALS=${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} JWT_KEY=${{secrets.JWT_KEY}} PROJECT_ID=${{secrets.GCLOUD_PROJECT_ID}} GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}} GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}} yarn test
        # env:
        #   JWT_KEY: ${{secrets.JWT_KEY}}
        #   GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
        #   GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        #   PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        #   APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
